export const songbank = [
  {
    id: 1,
    title: 'Alive',
    artist: 'Pearl Jam',
    genre: 'Rock',
    lyrics: 'URL',
  },
  {
    id: 2,
    title: 'Across The Universe',
    artist: 'The Beatles',
    genre: 'Rock',
    lyrics: 'URL',
  },
  {
    id: 3,
    title: 'Take On Me',
    artist: 'A-ha!',
    genre: 'Pop',
    lyrics: 'URL',
  },
  {
    id: 4,
    title: 'Comfortably Numb',
    artist: 'Pink Floyd',
    genre: 'Rock',
    lyrics: 'URL',
  },
  {
    id: 5,
    title: 'Patience',
    artist: "Guns n' Roses",
    genre: 'Acoustic',
    lyrics: 'URL',
  },
  {
    id: 6,
    title: 'Nothing Compares',
    artist: 'Chris Cornell',
    genre: 'Acoustic',
    lyrics: 'URL',
  },
  {
    id: 7,
    title: 'Future Days',
    artist: 'Pearl Jam',
    genre: 'Rock',
    lyrics: 'URL',
  },
  {
    id: 8,
    title: 'Pasilyo',
    artist: 'Sunkissed Lola',
    genre: 'OPM',
    lyrics: 'URL',
  },
  {
    id: 9,
    title: 'Buwan',
    artist: 'Juan Karlos',
    genre: 'OPM',
    lyrics: 'URL',
  },
  {
    id: 10,
    title: 'Angels Or Devils',
    artist: 'Dishwalla',
    genre: 'Alternative',
    lyrics: 'URL',
  },
  {
    id: 11,
    title: 'Plush',
    artist: 'Stone Temple Pilots',
    genre: 'Rock',
    lyrics: 'URL',
  },
  {
    id: 12,
    title: 'Everlong',
    artist: 'Foo Fighters',
    genre: 'Alternative',
    lyrics: 'URL',
  },
  {
    id: 13,
    title: 'Creep',
    artist: 'Radiohead',
    genre: 'Alternative',
    lyrics: 'URL',
  },
  {
    id: 14,
    title: 'Wonderful Tonight',
    artist: 'Eric Clapton',
    genre: 'Soft Rock',
    lyrics: 'URL',
  },
  {
    id: 15,
    title: 'Prinsesa',
    artist: 'Teeth',
    genre: 'OPM',
    lyrics: 'URL',
  },
  {
    id: 16,
    title: 'While My Guitar Gently Weeps',
    artist: 'The Beatles',
    genre: 'Rock',
    lyrics: 'URL',
  },
  {
    id: 17,
    title: 'Drive',
    artist: 'Incubus',
    genre: 'Alternative',
    lyrics: 'URL',
  },
  {
    id: 18,
    title: 'Iris',
    artist: 'Goo Goo Dolls',
    genre: 'Alternative',
    lyrics: 'URL',
  },
  {
    id: 19,
    title: '214',
    artist: 'Rivermaya',
    genre: 'OPM',
    lyrics: 'URL',
  },
  {
    id: 20,
    title: 'Noypi',
    artist: 'Bambpp',
    genre: 'OPM',
    lyrics: 'URL',
  },
  {
    id: 21,
    title: "Poorman's Grave",
    artist: 'Eraserheads',
    genre: 'OPM',
    lyrics: 'URL',
  },
  {
    id: 22,
    title: 'Alive',
    artist: 'Pearl Jam',
    genre: 'Rock',
    lyrics: 'URL',
  },
  {
    id: 23,
    title: 'Tensionado',
    artist: 'Soapdish',
    genre: 'OPM',
    lyrics: 'URL',
  },
  {
    id: 24,
    title: 'Your Love',
    artist: 'Alamid',
    genre: 'OPM',
    lyrics: 'URL',
  },
  {
    id: 25,
    title: 'Parting Time',
    artist: 'Rockstar',
    genre: 'OPM',
    lyrics: 'URL',
  },
  {
    id: 26,
    title: 'Kaleidoscope',
    artist: 'Francis Magalona',
    genre: 'OPM',
    lyrics: 'URL',
  },
  {
    id: 27,
    title: 'Yesterday',
    artist: 'The Beatles',
    genre: 'Rock',
    lyrics: 'URL',
  },
  {
    id: 28,
    title: 'Landslide',
    artist: 'Fleetwood Mac',
    genre: 'Pop',
    lyrics: 'URL',
  },
  {
    id: 29,
    title: 'More Than Words',
    artist: 'Extreme',
    genre: 'Acoustic',
    lyrics: 'URL',
  },
  {
    id: 30,
    title: 'Change The World',
    artist: 'Eric Clapton',
    genre: 'Acoustic',
    lyrics: 'URL',
  },
];
